name: Generate profile README

on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest

    environment:
      name: production

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Render GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_GITHUB_TOKEN }}
